// tempplate
// {
//   cardName: '',
//   cardDescription: '',
//   cardAttr1: '',
//   cardAttr2: '',
//   cardAttr3: '',
//   cardImage: '',
//   cardRare: '',
//   cardTrunfo: false,
// },

const presetCards = [
  {
    cardName: 'Goku',
    cardDescription: 'Oi, eu sou o goku!',
    cardAttr1: '50',
    cardAttr2: '45',
    cardAttr3: '30',
    cardImage: 'https://sm.ign.com/ign_br/screenshot/default/goku_trw2.jpg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Goku Blue',
    cardDescription: 'Acima do poder de um SSJ Deus!',
    cardAttr1: '75',
    cardAttr2: '70',
    cardAttr3: '75',
    cardImage: 'https://i0.wp.com/gamehall.com.br/wp-content/uploads/2018/03/Goku-SSJ-Blue.png?ssl=1',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Vegeta',
    cardDescription: 'O príncipe dos sayajins!!',
    cardAttr1: '55',
    cardAttr2: '40',
    cardAttr3: '35',
    cardImage: 'https://store-images.s-microsoft.com/image/apps.49028.64745599684926622.3a631981-7acb-462b-8e01-78b4d9a96ba6.eb0f9ead-7286-4bce-862b-8546769bcc78?q=90&w=480&h=270',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Vegeta Blue',
    cardDescription: 'Se você consegue eu também consigo Kakaroto!',
    cardAttr1: '80',
    cardAttr2: '65',
    cardAttr3: '75',
    cardImage: 'https://i0.wp.com/oportaln10.com.br/dinastianerd/wp-content/uploads/2021/04/image_ezbj.jpg?fit=1920%2C1080&ssl=1',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Gohan SSJ',
    cardDescription: 'Primeiro filho de goku! Só luta quando é preciso, prefere estudar.',
    cardAttr1: '30',
    cardAttr2: '25',
    cardAttr3: '50',
    cardImage: 'https://c4.wallpaperflare.com/wallpaper/410/680/880/dragon-ball-dragon-ball-z-gohan-dragon-ball-kamehameha-hd-wallpaper-preview.jpg',
    cardRare: 'normal',
    cardTrunfo: false,
  },
  {
    cardName: 'Broly',
    cardDescription: 'O lendário SSJ, poder incomparável, mas descontrolado.',
    cardAttr1: '80',
    cardAttr2: '80',
    cardAttr3: '90',
    cardImage: 'https://c4.wallpaperflare.com/wallpaper/207/731/645/movie-dragon-ball-super-broly-broly-dragon-ball-hd-wallpaper-preview.jpg',
    cardRare: 'muito raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Majin Vegeta',
    cardDescription: 'Vale tudo pra dar uns tapa no Kakaroto.',
    cardAttr1: '60',
    cardAttr2: '65',
    cardAttr3: '60',
    cardImage: 'https://c4.wallpaperflare.com/wallpaper/547/981/164/dragon-ball-vegeta-gohan-super-saiyan-wallpaper-preview.jpg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Frieza',
    cardDescription: 'Cabeça de bola de gude.',
    cardAttr1: '60',
    cardAttr2: '70',
    cardAttr3: '50',
    cardImage: 'https://asset-a.grid.id/crop/0x0:0x0/x/photo/2022/08/18/dragon-ball-friezajpg-20220818021242.jpg',
    cardRare: 'raro',
    cardTrunfo: false,
  },
  {
    cardName: 'Goku UI',
    cardDescription: 'Superando o nível dos Deuses!!',
    cardAttr1: '90',
    cardAttr2: '90',
    cardAttr3: '90',
    cardImage: 'https://assets.reedpopcdn.com/dxzrdjyu0aatk94.jpg/BROK/resize/1200x1200%3E/format/jpg/quality/70/dxzrdjyu0aatk94.jpg',
    cardRare: 'Muito Raro',
    cardTrunfo: false,
  },
];

export default presetCards;
